[package]
name = "dynamic-dependency-resolution-example"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.28", features = ["derive"] }
ferris-says = "0.3.2"
wasmtime = "29.0.1"
